/* eslint-disable no-sparse-arrays */
const { Client } = require("discord.js");
const client = new Client();

const prefix = "/drakesays";

/* Drake's lyrics
  ["lyric", "song", "album"]
  */
function getLyric() {
	const lyricsBae = [
		["We too deep in this thing, you'll never lose me", "U With Me?"],
		["Tryna give your ass the world", "U With Me?"],
		["You tip the scale when I weigh my options", "Redemption"],
		["This is not a fairytale, I already know how you like it", "Child's Play"],
		["You just like my sidekick, I just wanna wife, fulfill all your desires", "Fire & Desire"],
		["You don't need no one else, you don't need nobody else", "Hotline Bling"],
		["You got something that belongs to me", "Feel No Ways"],
		["I need you around, I need you", "With You"],
		["Let's do the things that we say on text", "Faithful"],
		["Baby, I like your style", "One Dance"],
		["I just wanna let you know that someone love you back", "Child's Play"],
		["Tell me should I cut these other girls right out of my life", "Fire & Desire"],
		["Tell me how you feel inside", "Fire & Desire"],
		["I figure out you, you figure out me", "Fire & Desire"],
		["Told you I got Zs for these other girls sleepin' on 'em, girl, I'm sleepy", "Fire & Desire"],
		["Like it's going in the trunk, I put it all behind us", "Views"],
		["You and yours vs. me and mine", "Big Rings", "What a Time to Be Alive"],
		["And you know what I need from you when I get home", "Diamonds Dancing", "What a Time to Be Alive"],
		["2 in the morning my mind is on you, 4 in the morning it still hasn't moved", "Change Locations", "What a Time to Be Alive"],
		["Lobster and Celine for all my babies that I miss", "Jumpman", "What a Time to Be Alive"],
		["What would I do without you, my chargie? I don't feel that way with anybody", "Hush Up the Silence", ""],
		["I wanna put you in my life", "Hush Up the Silence", ""],
		["Your hair smell like the tropics, your body look nice", "Hush Up the Silence", ""],
		["I'm here for you, just tell me what you like", "Hush Up the Silence", ""],
		["Got my Spanish ting convinced that I know Spanish", "Sneakin'", ""],
		["She texting purple hearts, cause she know that we at war", "Sneakin'", ""],
		["But I stay down, girl I always stay down", "Furthest Thing", "Nothing Was the Same"],
		["It's yours that's for sure, that's for sure", "Wu-Tang Forever", "Nothing Was the Same"],
		["You're still the one that I adore", "Own It", "Nothing Was the Same"],
		["It ain't a secret, baby, everybody saw us", "Own It", "Nothing Was the Same"],
		["Next time I stand tall, I wanna be standin' for you", "Own It", "Nothing Was the Same"],
		["Next time I spend I want it all to be for you", "Own It", "Nothing Was the Same"],
		["Who better for you than the boy?", "From Time", "Nothing Was the Same"],
		["You're everything that I see", "Hold On, We're Going Home", "Nothing Was the Same"],
		["Cause you're a good girl and you know it", "Hold On, We're Going Home", "Nothing Was the Same"],
		["How beautiful our kids would be", "Connect", "Nothing Was the Same"],
		["I treat you good girl like you're famous", "Connect", "Nothing Was the Same"],
		["Your hustle don't ever go unnoticed baby", "305 to My City", "Nothing Was the Same"],
		["Let me put something in your life", "Practice", "Take Care"],
		["One more chance to make it right, I think I'm using it right now", "Hate Sleeping Alone", "Take Care"],
		["Passionate from miles away", "Passionfruit", "More Life"],
		["God knows I'm trying for you", "Madiba Riddim", "More Life"],
		["Don't switch on me, I got big plans", "Blem", "More Life"],
		["We need to forward to the islands and get you gold, no spray tans", "Blem", "More Life"],
		["I know we canâ€™t keep it together forever, cause youâ€™re crazy sometimes", "Blem", "More Life"],
		["My side girl got a 5S with the screen cracked, still hit me back right away,", "Portland", "More Life"],
		["I'm still posted up where you first found me", "Nothings Into Somethings", "More Life"],
		["Out of body, that's just how I feel when I'm around you, shawty", "Teenage Fever", "More Life"],
		["You say the word, I'm on the way", "Teenage Fever", "More Life"],
		["Sometimes I gotta just make sure that I didn't lose you", "Lose You", "More Life"],
		["You said that you think about me every day", "Since Way Back", "More Life"],
		["See you when I see the real thing getting realer and realer", "Ice Melts", "More Life"],
		["You know how I like it when you loving on me", "God's Plan", "Scorpion"],
		["Don't pull up at 6 AM to cuddle with me", "God's Plan", "Scorpion"],
		["Girls hugging me then asking me, \"What scent that is, boy?\"", "Diplomatic Immunity", "Scary Hours"],
		["She is not the type that likes to take things slowly", "Elevate", "Scorpion"],
		["You know how I like it when you loving on me", "God's Plan", "Scorpion"],
		["Treat you like princess", "Peak", "Scorpion"],
		["I want my baby to have your eyes", "Finesse", "Scorpion"],
		["When I take you shoppin' you spend it like you earned it", "In My Feelings", "Scorpion"],
		["I thought you were the one from the jump that confirmed it", "In My Feelings", "Scorpion"],
		["You got options, but I been chosen", "Final Fantasy", "Scorpion"],
		["To deal with you the way you like", "Final Fantasy", "Scorpion"],
	];

	const lyricsOther = [
		["Crest white smile on my face", "Bring It Back", ""],
		["Heavy on the watch", "Bring It Back", ""],
		["Name ringing like a Migo trap phone", "Walk It Talk It", ""],
		["I gotta stay in my zone", "Walk It Talk It", ""],
		["Where your real friends at?", "Started from the Bottom", "Nothing Was the Same"],
		["All this for my family, man, I try my hardest", "Pop Style", "Views"],
		["Seen this movie a hundred times, I know where it's headed", "Survival", "Scorpion"],
		["Always got a ace up my sleeve for whatever was dealt", "Survival", "Scorpion"],
		["I stopped askin' myself and I started feelin' myself", "Survival", "Scorpion"],
		["Now I gotta deal with all this drama and deal with myself", "Survival", "Scorpion"],
		["Only obligation is to tell it straight. So much on my plate I gotta delegate", "Elevate", "Scorpion"],
		["All these followers but who gon' follow me to the end. I guess I'll make it to the end and I'ma find out then", "Emotionless", "Scorpion"],
		["Got a lot of blood and it's cold. They keep tryna get me for my soul", "I'm Upset", "Scorpion"],
		["I still got like seven years of doin' what I want", "I'm Upset", "Scorpion"],
		["I've never been the type to make amends", "8 Out of 10", "Scorpion"],
		["I don't like to talk when there's nothin' else left to say", "8 Out of 10", "Scorpion"],
		["Whatever you did, it is what it is", "Mob Ties", "Scorpion"],
		["They want me gone but don't know why", "Mob Ties", "Scorpion"],
		["S Class, G Class, lotta class", "Mob Ties", "Scorpion"],
		["Lead the league in scorin', man, but look at my assists", "Mob Ties", "Scorpion"],
		["I do not forget a thing, I'm patient, it's a gift ", "Mob Ties", "Scorpion"],
		["Try to tell 'em they ain't got to do it, they insist ", "Mob Ties", "Scorpion"],
		["Worms, I just opened up a can of those", "Sandra's Rose", "Scorpion"],
		["Life too short, I gotta get it before they blow the whistle", "Sandra's Rose", "Scorpion"],
		["I'm the chosen one, flowers never pick themselves", "Sandra's Rose", "Scorpion"],
		["Can of worms and I'm the early bird", "Sandra's Rose", "Scorpion"],
		["I'm so proud of who I've become", "Talk Up", "Scorpion"],
		["Intentions are pure, they cannot tell me relax", "Talk Up", "Scorpion"],
		["My money is young, my problems are old. I promise I'm bridgin' the gap", "Talk Up", "Scorpion"],
		["Only holdin' up I do is my end of the bargain", "Is There More", "Scorpion"],
		["Only beggin' that I do is me beggin' your pardon", "Is There More", "Scorpion"],
		["Only lyin' I do is lyin' out in the tropics", "Is There More", "Scorpion"],
		["Only cryin' I do is cryin' from laughin' 'bout it", "Is There More", "Scorpion"]
		// eslint-disable-next-line no-unexpected-multiline
			["Only rest that I do is \"Where the rest of my commas?\"", "Is There More", "Scorpion"],
		["When life comin' at you from all angles and sides", "Is There More", "Scorpion"],
		["They don't wanna see that you smilin' from inside", "Is There More", "Scorpion"],
		["I'm in control of my destiny, never in doubt", "Is There More", "Scorpion"],
		["They say take the good with the bad, I'll take it without", "Is There More", "Scorpion"],
		["My moral compass is janky, it breaks in the South", "Is There More", "Scorpion"],
		["Too many Walt Disney characters, mouses and goofs", "Is There More", "Scorpion"],
		["It's too bad reality checks don't cover the balances due", "Is There More", "Scorpion"],
		["What you got, time on your hands or time on your side?", "Is There More", "Scorpion"],
		["Is there more to life than just when I'm feelin' alive?", "Is There More", "Scorpion"],
		["Talk used to be cheap, nowadays it's free", "Peak", "Scorpion"],
		["I found my peace, I'm about to say my piece", "Peak", "Scorpion"],
		["You gon' make me turn up on you", "Peak", "Scorpion"],
		["I'm going against my own advice", "Finesse", "Scorpion"],
		["I can't even lie, I'd rather stay inside", "Finesse", "Scorpion"],
		["Work all winter, shine all summer", "That's How You Feel", "Scorpion"],
		["Drink 'til the sun up. Grind 'til you come up", "That's How You Feel", "Scorpion"],
		["Look the new me is really still the real me", "In My Feelings", "Scorpion"],
		["'Cause I've been goin' off and they don't know when it's stoppin'", "In My Feelings", "Scorpion"],
		["I like best when you're fresh faced and no foundation", "Final Fantasy", "Scorpion"],
		["I always need a glass of wine by sundown", "Final Fantasy", "Scorpion"],
	];

	const lyricsCrewLove = [
		["We been brothers since Versace bando", "Walk It Talk It", ""],
		["You gon' make me call my bros for assistance", "Sneakin'", ""],
		["I only link with the real ones", "Wanna Know (Remix)", ""],
		["Me and my friends we got money to spend", "Change Locations", "What a Time to Be Alive"],
		["Me and my broski are twins, but we don't look alike", "Gyalchester", "More Life"],
		["Imagine if I never met the broskies", "God's Plan", "Scary Hours"],
		["Me and all the dogs acting like some dogs", "Can't Have Everything", "More Life"],
		["Strength and guidance, all that I'm wishing for my friends", "One Dance", "Views"],
		["More time with family and friends, more life", "Two Birds, One Stone", ""],
		["I'mma see a lot of blessings for my friends soon", "Sneakin'", ""],
		["Same city, same friends if you're looking for me", "Connect", "Nothing Was the Same"],
		["I'm with everyone that I was here with in the first place", "Used to This", ""],
		["Jumpman, Jumpman, Jumpman, them boys up to something", "Jumpman", "What a Time to Be Alive"],
		["I can't really see another squad tryna' cross us, naw", "No Tellin'", "If You're Reading This It's Too Late"],
		["I live for the nights that I can't remember with the people that I won't forget", "Show Me a Good Time Lyrics", "Thank Me Later"],
		["My team good, we don't really need a mascot", "The Motto", ""],
		["Nobody really likes us except us", "6 Man", "If You're Reading This It's Too Late"],
		["No new friends", "No New Friends", ""],
		["I got a really big team and they need some really big rings", "Big Rings", "What a Time to Be Alive"],
		["You and yours vs. me and mine", "Big Rings", "What a Time to Be Alive"],
		["Are we talkin' teams?", "Big Rings", "What a Time to Be Alive"],
		["Love my brothers, cut 'em in on anything", "Nonstop", "Scorpion"],
		["Me and all the guys found a better way", "Elevate", "Scorpion"],
		["I gotta bring my brothers or else I feel out of place", "Emotionless", "Scorpion"],
		["Skit around ends with the bros and I'm kitted to the toes", "Can't Take a Joke", "Scorpion"],
		["We live by the code, reputation to uphold", "Can't Take a Joke", "Scorpion"],
		["I be tryna laugh with the bros but they can't take a joke", "Can't Take a Joke", "Scorpion"],
		["Ten of us, we movin' as one", "Talk Up", "Scorpion"],
	];

	// Lit lyrics
	const lyricsLit = [
		["My luck is a sure thing cause I'm living right", "Keep the Family Close", "Views"],
		["Everything I said, it happened", "Hype", "Views"],
		["The only thing I did to end up here was put the work in, and did it with a purpose", "Weston Road Flows", "Views"],
		["Years go by too fast, I can't keep track", "Too Good", "Views"],
		["I got a pure soul, I don't do the hate", "Views", "Views"],
		["I'd share more of my story but you wouldn't believe it", "Views", "Views"],
		["Look what I've done in my life", "Hype", "Views"],
		["You would think it's all mine, the way I took it", "Faithful", "Views"],
		["All I do is hang with the young and heartless", "Pop Style", "Views"],
		["Last night I think I lost my patience", "Too Good", "Views"],
		["You could throw curve balls but I got the glove fitted", "Views", "Views"],
		["It's only up from here, I promise, you just gotta wait", "Views", "Views"],
		["I keep it a hundred like I'm running a fever", "Views", "Views"],
		["I got my foot on their neck and my foot on the gas", "Digital Dash", "What a Time to Be Alive"],
		["Cause I got a really big team, and they need some really big rings", "Big Rings", "What a Time to Be Alive"],
		["Man, what a time to be alive", "Big Rings", "What a Time to Be Alive"],
		["Soon as night fall, that's when we lock in", "Live from the Gutter", "What a Time to Be Alive"],
		["These the times we gotta live through", "Live from the Gutter", "What a Time to Be Alive"],
		["I wake up on a daily basis, I count the money man, I'm already rich", "Scholarships", "What a Time to Be Alive"],
		["Wake up and pray every morning, Demons, they callin' my soul", "Scholarships", "What a Time to Be Alive"],
		["I need acknowledgement, If I got it then tell me I got it then", "Scholarships", "What a Time to Be Alive"],
		["I be in the club with the bands, like I got the keyboard and the drums with me", "Plastic Bag", "What a Time to Be Alive"],
		["This a good night to dance on me", "Plastic Bag", "What a Time to Be Alive"],
		["Out here trying to spread the movement", "30 for 30 Freestyle", "What a Time to Be Alive"],
		["I thought you wanted yours like I want mine", "30 for 30 Freestyle", "What a Time to Be Alive"],
		["I don't usually do this unless I'm drunk or I'm high, but I'm both right now", "Both", ""],
		["Shout-out Yachty but this ain't a Lil Boat", "Both", ""],
		["The power of the mind is not a joke", "Both", ""],
		["No one looks surprised cause we used to this", "Used to This", ""],
		["Imma make sure that we get used to this", "Used to This", ""],
		["Treat my brother's kids like they one of my kids", "Used to This", ""],
		["Eyes getting low but I'm still observing, I see you lurking", "Used to This", ""],
		["Never made a move out here unless I was certain", "Used to This", ""],
		["Streets unruly, More life for my brother's tryna better things", "Wanna Know (Remix)", ""],
		["Spotted everywhere, like Dalmatian", "Two Birds, One Stone", ""],
		["Being awake is what all my dreams were like, back when the bar that I had set for myself was out of sight", "Two Birds, One Stone", ""],
		["I'm down 200 in Vegas but winning life on a daily basis", "Two Birds, One Stone", ""],
		["This is all God's doing, man, you can't plan it", "Sneakin'", ""],
		["Can't afford mistakes, not on this end", "Sneakin'", ""],
		["I been tryna change life around for everyone I know", "Sneakin'", ""],
		["I'm livin' like I'm out here on my last adventure", "Tuscan Leather", "Nothing Was the Same"],
		["Started from the bottom, now we here", "Started from the Bottom", "Nothing Was the Same"],
		["Rich enough that I don't have to tell 'em that I'm rich", "Tuscan Leather", "Nothing Was the Same"],
		["On a mission tryna shift the culture", "Tuscan Leather", "Nothing Was the Same"],
		["Born a perfectionist, guess that makes me a bit obsessive", "Tuscan Leather", "Nothing Was the Same"],
		["My life's a completed checklist", "Tuscan Leather", "Nothing Was the Same"],
		["Just give it time, we'll see who's still around a decade from now", "Tuscan Leather", "Nothing Was the Same"],
		["Lately I've been feelin' like Guy Pearce in Memento", "Tuscan Leather", "Nothing Was the Same"],
		["Wanted to tell you, \"Accept yourself\", You don't have to prove it to no one except yourself", "Tuscan Leather", "Nothing Was the Same"],
		["Somewhere between I want it and I got it", "Furthest Thing", "Nothing Was the Same"],
		["You know that paper my passion", "Furthest Thing", "Nothing Was the Same"],
		["Naked women swimmin', that's just how I'm livin'", "Furthest Thing", "Nothing Was the Same"],
		["Donate a million to some children, that's just how I'm feelin'", "Furthest Thing", "Nothing Was the Same"],
		["I just build and build more", "Furthest Thing", "Nothing Was the Same"],
		["I done kept it real from the jump", "Started from the Bottom", "Nothing Was the Same"],
		["Story stayed the same, I never changed it", "Started from the Bottom", "Nothing Was the Same"],
		["When the last time you did somethin' for the first time?", "Own It", "Nothing Was the Same"],
		["It's a mission, tryna fight to the finish", "Worst Behavior", "Nothing Was the Same"],
		["Enough to make you throw up, man it's gross what I net", "Worst Behavior", "Nothing Was the Same"],
		["I like when money makes a difference but don't make you different", "From Time", "Nothing Was the Same"],
		["Summer is comin' know you could feel it", "Connect", "Nothing Was the Same"],
		["I send all my money to banks in the islands, and eat with Italians", "The Language", "Nothing Was the Same"],
		["I'm quiet with it, I just ride with it", "Too Much", "Nothing Was the Same"],
		["Just talkin' women and vino", "Pound Cake / Paris Morton Music 2", "Nothing Was the Same"],
		["Overly focused, it's far from the time to rest now", "Pound Cake / Paris Morton Music 2", "Nothing Was the Same"],
		["I hear you talking, say it twice so I know you meant it", "Pound Cake / Paris Morton Music 2", "Nothing Was the Same"],
		["Tables turn, bridges burn, you live and learn", "Pound Cake / Paris Morton Music 2", "Nothing Was the Same"],
		["You know it's real when you are who you think you are", "Pound Cake / Paris Morton Music 2", "Nothing Was the Same"],,
		["We had the type of nights where morning comes too soon", "Come Thru", "Nothing Was the Same"],
		["Lookin' for the right way to do the wrong things", "Lord Knows", "Take Care"],
		["Word on road is the clique about to blow", "Cameras", "Drake"],
		["Summer's mine, I swear I said about a hundred times", "Good Ones Go (Interlude)", "Take Care"],
		["Live for today, plan for tomorrow, party tonight", "The Real Her", "Take Care"],
		["The weekend's here, started it right", "The Real Her", "Take Care"],
		["You know it's real when your latest nights are your greatest nights", "The Ride", "Take Care"],
		["I'm with my whole set, tennis matches at the crib", "Worst Behavior", "Nothing Was the Same"],
		["Hate to leave the city, but I've got to do the overtime", "Worst Behavior", "Nothing Was the Same"],
		["More life, more everything", "Free Smoke", "More Life"],
		["Passin' up on my old ways", "Passionfruit", "More Life"],
		["Never chase it, let it come to you", "Jorja Interlude", "More Life"],
		["More chune for your headtop, so watch how you speak on my name", "Jorja Interlude", "More Life"],
		["Your mind impure, soul I possess", "Madiba Riddim", "More Life"],
		["Who keeps bringing more? I've had too many", "Blem", "More Life"],
		["I'm blem for real, I might just say how I feel", "Blem", "More Life"],
		["I know what I like, I know how I wanna live my life, I donâ€™t need no advice", "Blem", "More Life"],
		["Tat on my ribs like I do not know what permanent is", "Gyalchester", "More Life"],
		["Stay at the top like I'm stuck", "Gyalchester", "More Life"],
		["She wanna get married tonight, but I can't take a knee, cause I'm wearin' all white", "Gyalchester", "More Life"],
		["I don't take naps. Me and the money are way too attached to go and do that", "Gyalchester", "More Life"],
		["Tryna show the dogs brighter days", "Portland", "More Life"],
		["It's a marathon, not a sprint, but I still gotta win the race", "Sacrifices", "More Life"],
		["How long I been on this streak? Dream about work in my sleep", "KMT", "More Life"],
		["Life for my bruddas is deep, long as they all on they feet", "KMT", "More Life"],
		["Went and got diplomas, and we still going dumb", "Lose You", "More Life"],
		["I'm in it for the glory, not the honor mention", "Lose You", "More Life"],
		["Better attitude, we'll see where it gets me", "Lose You", "More Life"],
		["I know I deserve more, I just never said it", "Lose You", "More Life"],
		["People like you more when your working towards something, not when you have it", "Lose You", "More Life"],
		["You're mindful of it all when your mind full of it all", "Lose You", "More Life"],
		["It's the boy, but I'm still the man", "Can't Have Everything", "More Life"],
		["I don't stop, man I'm stuck on go", "Can't Have Everything", "More Life"],
		["I went off in the '16, give me '17", "Can't Have Everything", "More Life"],
		["Want a lot, can't have everything but I want everything", "Can't Have Everything", "More Life"],
		["Watch out for me, I'm about to glow", "Glow", "More Life"],
		["Just when it look out of reach, I reach back like one-three", "Fake Love", "More Life"],
		["Vibe switch like night and day", "Fake Love", "More Life"],
		["How I go from 6 to 23 like I'm LeBron?", "Nonstop"],
		["Future took the business and ran it for me, I let Ollie take the owl told him brand it for me, I get 2 million a pop and that’s standard for me like I went blind, dog, you gotta hand it to me", "Nonstop"],
		["More blessings because I'm generous", "Do Not Disturb", "More Life"],
		["More Life", "Do Not Disturb", "More Life"],
		["They gon' tell the story, it was different with me", "God's Plan", "Scorpion"],
		["Might go down a G.O.D.", "God's Plan", "Scorpion"],
		["God's plan, I can't do this on my own", "God's Plan", "Scorpion"],
		["The one with the fewest lies and the truest ties", "Diplomatic Immunity", "Scary Hours"],
		["Champagne is the alias", "Diplomatic Immunity", "Scary Hours"],
		["I got the sauce and now shorties keep claiming preggo", "Diplomatic Immunity", "Scary Hours"],
		["That just pushed me to do the things we all couldn't", "Diplomatic Immunity", "Scary Hours"],
		["I don't know nobody else that's doing this", "Nonstop", "Scorpion"],
		["Now they wanna know me since I hit the top", "Nonstop", "Scorpion"],
		["This a Rollie, not a stopwatch, it don't ever stop", "Nonstop", "Scorpion"],
		["I wanna thank God for workin' way harder than Satan", "Elevate", "Scorpion"],
		["End up gettin' loose and gettin' pictures from my ex", "I'm Upset", "Scorpion"],
		["And I hardly take offense, money for revenge, man, that’s hardly an expense", "Nonstop"],
		["But I'm blessed, I just checked / Hate me, never met me in the flesh.", "I'm Upset"],
		["House on both coasts, but I live on the charts, I have tea with the stars and I swim with the sharks, and I see in the dark, wasn't this cold at the start, think my soul has been marked, there's a hole in my heart.", "Survival"],
		["I find it funny how I keep on talkin' and commas increase", "Sandra's Rose", "Scorpion"],
		["I don't know who's protectin' me but we hit it off", "Sandra's Rose", "Scorpion"],
	];

	// Savage lyrics
	const lyricsSavage = [
		["I can't tell you if she's yours or mine", "Still Here", "Views"],
		["Tell me how you really feel, tell me how you really feel", "Grammys", "Views"],
		["Y'all a whole lot of things but you still ain't this", "Grammys", "Views"],
		["They'd rather run up on me than towards their goals", "Views", "Views"],
		["You got exactly what you asked for", "Hotline Bling", "Views"],
		["Three dots, you thinkin' of a reaction still", "U With Me?", "Views"],
		["Your best day is my worst day", "Weston Road Flows", "Views"],
		["You don't know what you just started", "Pop Style", "Views"],
		["Free time is costing me more than it seems", "Too Good", "Views"],
		["Karma's such a thing of beauty", "Views", "Views"],
		["This year for Christmas I just want apologies", "Redemption", "Views"],
		["Tryna satisfy everybody, it's like they can't get enough", "Redemption", "Views"],
		["You hate your life, just be honest", "Digital Dash", "What a Time to Be Alive"],
		["I do not chase girls, but they run a mile for me", "Big Rings", "What a Time to Be Alive"],
		["They don't want no smoke, they don't want no issue", "Live from the Gutter", "What a Time to Be Alive"],
		["Talking to your friends like you usually do, telling them I never spend time with you", "Diamonds Dancing", "What a Time to Be Alive"],
		["You look drained, you look exhausted, girl them late nights ain't good for you", "Diamonds Dancing", "What a Time to Be Alive"],
		["Don't hit me up when it's good for you", "Diamonds Dancing", "What a Time to Be Alive"],
		["Who really think they can get in the way?", "I'm the Plug", "What a Time to Be Alive"],
		["I gave it to her then I curved her", "I'm the Plug", "What a Time to Be Alive"],
		["Way too many questions, you must think I trust you", "Jumpman", "What a Time to Be Alive"],
		["And your absence is very concerning, It's like you went on vacation with no plan of returning", "30 for 30 Freestyle", "What a Time to Be Alive"],
		["I'm just in a different space and I choose to embrace it", "30 for 30 Freestyle", "What a Time to Be Alive"],
		["You think I need you but I don't", "Both", ""],
		["Thought they had my back against the wall", "Used to This", ""],
		["Free smoke, anybody want it they can get it", "Wanna Know (Remix)", ""],
		["Years ago they didn't wanna know", "Wanna Know (Remix)", ""],
		["Could feel my hand getting tired from holding the grudges", "Two Birds, One Stone", ""],
		["People too scared to tell the truth, so it's all dares", "Two Birds, One Stone", ""],
		["Tell me who dissin', I got some things that'll hit the culprit", "Tuscan Leather", "Nothing Was the Same"],
		["Boys tell stories 'bout the man", "Started from the Bottom", "Nothing Was the Same"],
		["You ain't ever worried cause he's not who he pretends to be", "Wu-Tang Forever", "Nothing Was the Same"],
		["Ain't much out there to have feelings for", "Own It", "Nothing Was the Same"],
		["Y'all don't even really check for me", "Own It", "Nothing Was the Same"],
		["Got you thinkin' that I'm different these days", "Own It", "Nothing Was the Same"],
		["Always hated the boy, but now the boy is the man", "Worst Behavior", "Nothing Was the Same"],
		["I should let you know ahead I'm comin' back on my worst behavior", "Worst Behavior", "Nothing Was the Same"],
		["Jealousy in the air tonight, I could tell", "The Language", "Nothing Was the Same"],
		["You don't even know about the stuff that I been through", "The Language", "Nothing Was the Same"],
		["Come get your girl, she been here for three days, and she way too attached to me", "The Language", "Nothing Was the Same"],
		["Took a while, got the jokers out of the deck now", "Pound Cake / Paris Morton Music 2", "Nothing Was the Same"],
		["I'm the big homie, they still be tryna lil bro me, dog", "Pound Cake / Paris Morton Music 2", "Nothing Was the Same"],
		["Understand that I'm not doin' it the same man, I'm doing it better", "Pound Cake / Paris Morton Music 2", "Nothing Was the Same"],
		["Jealousy is just love and hate at the same time", "Over My Dead Body", "Take Care"],
		["I'm the reason why you always getting faded", "Shot for Me", "Take Care"],
		["I can see it in your eyes, you're angry", "Shot for Me"],
		["Prayin' for your happiness, hope that you recover", "Shot for Me", "Take Care"],
		["Places they say they've been, we actually going for real", "Lord Knows", "Take Care"],
		["Free smoke, free smoke", "Free Smoke", "More Life"],
		["You tryna date her and she been, let me walk twice", "No Long Talk", "More Life"],
		["Worried about taking my lane, they ain't even got on my road", "Jorja Interlude", "More Life"],
		["I seen man turn fool for the money one too many times", "Madiba Riddim", "More Life"],
		["I seen some girls turn they back on they best friend from time", "Madiba Riddim", "More Life"],
		["I need you to stop runnin' back to your ex, he's a wasteman", "Blem", "More Life"],
		["They want me gone, wait for the kicker, bury me now and I only get bigger", "Gyalchester", "More Life"],
		["She complaining how I'm late, I ain't know it was a date", "Sacrifices", "More Life"],
		["I met someone new last night and we kicked it and I'm going back there tonight", "Teenage Fever", "More Life"],
		["Love is just not in my plans, not even takin' a chance", "KMT", "More Life"],
		["You don't know nothing about me", "KMT", "More Life"],
		["She say, \"Do you love me?\" I tell her, \"Only partly\" I only love my bed and my momma, I'm sorry", "God's Plan", "Scorpion"],
		["Pinky ring 'til I get a wedding ring", "Nonstop", "Scorpion"],
	];

	// Simp lyrics
	const lyricsSimp = [
		["Always saw you for what you could've been", "Keep the Family Close", "Views"],
		["When I needed you, you couldn't give me any advice, but you always had something to say every other time", "Keep the Family Close", "Views"],
		["I think we just get closer when we not together", "U With Me?", "Views"],
		["Girl, I had your back when all you used to do was front", "U With Me?"],
		["Your body language says it all, despite the things you said to me", "Feel No Ways", "Views"],
		["Feel like the difference between us really startin' to show", "Weston Road Flows", "Views"],
		["But it ain't how it always seems when it's so together", "Weston Road Flows", "Views"],
		["I don't know how to be there when you need me", "Too Good", "Views"],
		["Don't play the victim when you're with me", "Too Good", "Views"],
		["You should just be yourself, right now, you're someone else", "Hotline Bling", "Views"],
		["Feel like the difference between us really startin' to show", "Weston Road Flows", "Views"],
		["I'm searching for these words to say to you", "Redemption", "Views"],
		["I miss the feeling of you missing me", "Redemption", "Views"],
		["Redemption's on your mind when you think about me", "Redemption", "Views"],
		["Wonder what they'd do put in my position", "Redemption", "Views"],
		["Wonder if they wish it could've been different", "Redemption", "Views"],
		["Please give me time, cause I'm searchin' for these words to say to you", "Redemption", "Views"],
		["Just ignore all the skeletons in my closet", "Redemption", "Views"],
		["Who's gonna save me when I need savin'?", "Redemption", "Views"],
		["Busy as usual but we should make some time", "With You", "Views"],
		["Mixing vodka and emotions", "With You", "Views"],
		["You take my love for granted, I just don't understand it", "Too Good", "Views"],
		["It can't end like this, we gotta take time with this", "Too Good", "Views"],
		["How we let it get like this I don't know", "Diamonds Dancing", "What a Time to Be Alive"],
		["You should go back to him, perfect match for you, unstable", "Diamonds Dancing", "What a Time to Be Alive"],
		["I haven't even heard from you, not a single word from you", "Diamonds Dancing", "What a Time to Be Alive"],
		["My mind's not all there", "Two Birds, One Stone", ""],
		["We all wide awake late at night, thinking on what to change, If we do get to do it twice in another life", "Two Birds, One Stone", ""],
		["Now that feeling's gone like them old pictures", "Two Birds, One Stone", ""],
		["Mixin' liquor got us both twisted, words get so vicious", "Two Birds, One Stone", ""],
		["Girl, I love you, but I don't miss ya", "Two Birds, One Stone", ""],
		["Me, I don't judge, I'm just going off what the math is", "Two Birds, One Stone", ""],
		["Look you in the face, and it's just not the same", "Fake Love", ""],
		["It ain't been the same like before", "Sneakin'", ""],
		["That's a real one in your reflection without a follow, without a mention", "Nice for What"],
		["Look, I just flipped a switch, I don't know nobody else that's doin' this", "Nonstop"],
		["All my exes live in Texas like I'm George Strait", "HYFR"],
		["So we took it to go, told them don't even plate it", "HYFR"],
		["I learned Hennessy and enemies is one hell of a mixture", "HYFR"],
		["I never started nothin', I just finish things", "No Shopping", ""],
		["I dropped the ball on some personal stuff, I need to embrace it", "Tuscan Leather", "Nothing Was the Same"],
		["The furthest thing from perfect like everyone I know", "Furthest Thing", "Nothing Was the Same"],
		["I hate that you don't think I belong to ya", "Furthest Thing", "Nothing Was the Same"],
		["I made every woman feel like she was mine and no one else's", "Furthest Thing", "Nothing Was the Same"],
		["Gone all the time, even the important times", "Worst Behavior", "Nothing Was the Same"],
		["You act so different around me", "Hold On, We're Going Home", "Nothing Was the Same"],
		["Heard once that in dire times when you need a sign, that's when they appear", "Too Much", "Nothing Was the Same"],
		["I guess sometimes life forces us to calm down", "Pound Cake / Paris Morton Music 2", "Nothing Was the Same"],
		["We ain't spoke in so long, probably put me in the past", "Come Thru", "Nothing Was the Same"],
		["I guess that's just the motion", "The Motion", "Nothing Was the Same"],
		["They say love is in the air, so I hold my breath until my face turn purple", "HYFR"],
		["Met a female dragon, had a fire conversation", "HYFR"],
		["Red wine over Fed time", "Over My Dead Body"],
		["In the next life, I'm tryna stay paid when I die, put my money in the grave", "Money in the grave"],
		["You could DM my accountant my per diem six figures and I'm countin'", "Money in the grave"],
		["Are you down, are you down? Yeah, you all the way down, every time, every time, every time, every time", "We'll Be Fine"]
		// eslint-disable-next-line no-unexpected-multiline
			["I guess you lose some and win some", "Over My Dead Body", "Take Care"],
		["You believed in everything but me, girl, I don't get you", "Shot for Me", "Take Care"],
		["I really wish she had a different way of viewing things", "Shot for Me", "Take Care"],
		["Guess she don't have the time to kick it no more", "Marvin's Room", "Take Care"],
		["I might talk that real if you ask me what I care about", "Underground Kings", "Take Care"],
		["When a good thing goes bad it's not the end of the world", "Doing It Wrong", "Take Care"],
		["Just another kid that's going through life so worried that I won't be accepted", "Look What You've Done", "Take Care"],
		["Working with the negatives could make for better pictures", "HYFR", "Take Care"],
		["Where you at? I never see you", "Free Smoke", "More Life"],
		["Don't pick up the pieces, just leave it for now. They keep fallin' apart", "Passionfruit", "More Life"],
		["I cannot tell who is my friend", "Madiba Riddim", "More Life"],
		["I need distance between me and them", "Madiba Riddim", "More Life"],
		["Gonna have to teach me how to love you again", "Madiba Riddim", "More Life"],
		["My heart is way too frozen to get broken", "Madiba Riddim", "More Life"],
		["I heard you say things that you can't take back girl", "Madiba Riddim", "More Life"],
		["People change, I'm not surprised", "Madiba Riddim", "More Life"],
		["I wanna know, how come we can never slash and stay friends?", "Blem", "More Life"],
		["Youâ€™re not here and we both know why", "Blem", "More Life"],
		["Your heart is hard to carry after dark", "Teenage Fever", "More Life"],
		["You're to blame for what we could have been", "Teenage Fever", "More Life"],
		["Your friends are scared to tell you you're in too far", "Teenage Fever", "More Life"],
		["When did all the things I mean from the bottom of my heart start to lose meaning?", "Lose You", "More Life"],
		["I know what we're both thinking even when you're quiet", "Lose You", "More Life"],
		["I still have my guard up, blame this thing I'm part of", "Glow", "More Life"],
		["You see that I've been going through it, hoping everything's okay", "Since Way Back", "More Life"],
		["I can't help but wonder how you've been babe", "Since Way Back", "More Life"],
		["What are you on? Gotta let me know something", "Since Way Back", "More Life"],
		["I want you to myself, but I know you just left someone else", "Ice Melts", "More Life"],
		["Patient as could be but I still need some satisfaction, a little less talk and a little more action", "Ice Melts", "More Life"],
		["I wanna see you do more in this life if we taking it there", "Ice Melts", "More Life"],
		["Saw a side of myself that I just never knew", "Do Not Disturb", "More Life"],
		["Can't describe what my life is like when she asks about it", "Do Not Disturb", "More Life"],
		["Seasons go by like I'm binge watchin'", "Do Not Disturb", "More Life"],
		["I don't have no time to be no Romeo", "Do Not Disturb", "More Life"],
		["I don't wanna die for them to miss me", "God's Plan", "Scorpion"],
		["Hope I got some brothers that outlive me", "God's Plan", "Scorpion"],
		["But I've been drinkin' so much that I'ma call her anyway, and say…", "Marvin's Room"],
		["Touch if you need to, but I can't stay to hold you that's the wrong thing to do", "Doing It Wrong"],
		["Talk if you need to, but I can't stay to hear you that's the wrong thing to do", "Doing It Wrong"],
		["I feel good, sometimes I don't", "God's Plan", "Scorpion"],
		["Don't make me break your Kevin Hart, boy", "Over My Dead Body"],
		["I think maybe I was numb to it last year but you know I feel it now more than ever", "Over My Dead Body"],
		["And I was drinking at the Palms last night and ended up losing everything that I came with", "Over My Dead Body"],
		["I broke spirits that I never meant to", "Diplomatic Immunity", "Scary Hours"],
		["Tired of women that may tag me in pictures airing my dirty laundry", "Diplomatic Immunity", "Scary Hours"],
		["Wakin' up at 6 PM like, \"Where does the day go?\"", "Diplomatic Immunity", "Scary Hours"],
		["Closed off but I could never stay closed", "Diplomatic Immunity", "Scary Hours"],
		["Protection that God gave me", "Diplomatic Immunity", "Scary Hours"],
		["Inshallah, I hope the mission keeps on getting clearer", "Diplomatic Immunity", "Scary Hours"],
		["Think my soul has been marked, there's a hole in my heart", "Survival", "Scorpion"],
		["I know the truth is you won't love me until I'm gone", "Emotionless", "Scorpion"],
		["She don't even love me, she just puttin' on a front", "I'm Upset", "Scorpion"],
		["If I can't make it with you, I'll make it without", "Is There More", "Scorpion"],
		["I think you're changin' your mind. Startin' to see it in your eyes", "Summer Games", "Scorpion"],
		["Summer just started and we're already done", "Summer Games", "Scorpion"],
		["Be warm with me when it's freezin' outside", "Summer Games", "Scorpion"],
		["I kept it decent, even the secrets. Kept it between you and I", "Summer Games", "Scorpion"],
		["Breakin' me down when I'm already down", "Summer Games", "Scorpion"],
		["Leaving me, Dippin' out on me, Already got what you needed, I guess", "Jaded", "Scorpion"],
		["Learned yourself through me", "Jaded", "Scorpion"],
		["That's why I'm not with nobody. 'Cause I don't wanna hurt nobody", "Jaded", "Scorpion"],
		["Still got love for you, mami", "Jaded", "Scorpion"],
		["I know you wanna be somebody. Even if you gotta leave somebody", "Jaded", "Scorpion"],
		["Yes I'm hurting, yes I'm jaded", "Jaded", "Scorpion"],
		["I always want the truth, but it's dangerous", "Jaded", "Scorpion"],
		["Said you need some time but I should stick around, for what?", "Jaded", "Scorpion"],
		["You played me, you played me", "Jaded", "Scorpion"],
		["How you even managing to keep straight faces in all the pictures that I seen lately", "Jaded", "Scorpion"],
		["You're old enough, but you're still a baby", "Jaded", "Scorpion"],
		["Had a man last year, life goes on", "Nice For What", "Scorpion"],
		["That's a real one in your reflection", "Nice For What", "Scorpion"],
		["Can't be in a room with you and stand on different sides, one thing at a time I have to learn to hide.", "Finesse", "Scorpion"],
		["You stay on my mind all the time", "Finesse", "Scorpion"],
		["Who's gonna love you on your worst day?", "Ratchet Happy Birthday", "Scorpion"],
		["I miss the days that you was all mine", "Ratchet Happy Birthday", "Scorpion"],
		["Haven't been official in a long time", "Ratchet Happy Birthday", "Scorpion"],
		["To be, to feel, and fill that emptiness inside you", "Ratchet Happy Birthday", "Scorpion"],
		["Time gets to tickin' and it takes a toll", "That's How You Feel", "Scorpion"],
		["Sidetracking me when I was good to you. You were somebody I would stand behind", "That's How You Feel", "Scorpion"],
		["Assuming the worst 'cause I haven't heard from you all weekend", "After Dark", "Scorpion"],
		["Your silence is drivin' me up the wall", "After Dark", "Scorpion"],
		["I cannot tell if you're ducking calls or missing calls", "After Dark", "Scorpion"],
		["I wanna make you a priority, I wanna let you know there's more to me", "After Dark", "Scorpion"],
		["I wanna have your faith restored in me", "After Dark", "Scorpion"],
		["Being honest, I don't really know what patience is", "Final Fantasy", "Scorpion"],
		["Now it's rough times, I'm out here on front lines", "March 14 ", "Scorpion"],
		["I wanted it to be different because I've been through it", "March 14 ", "Scorpion"],
	];

	// IDFWU lyrics
	const lyricsIdfwu = [
		["I had to let go of us to show myself what I could do", "Feel No Ways", "Views"],
		["My enemies wanna be friends with my other enemies, I don't let it get to me", "Hype", "Views"],
		["You shouldn't speak on me, period", "Hype", "Views"],
		["I gave your nickname to someone else", "Redemption", "Views"],
		["They don't need to know all of our business", "Child's Play", "Views"],
		["I never tag no one in, I'd rather get you myself", "Views", "Views"],
		["If I was you, I wouldn't like me either", "Views", "Views"],
		["I've stopped listening to things you say 'cause you don't mean it anyway", "Feel No Ways", "Views"],
		["Told myself never again, I donâ€™t let nobody in", "Digital Dash", "What a Time to Be Alive", "Views"],
		["I don't forget or forgive", "Digital Dash", "What a Time to Be Alive"],
		["If you come here trying to take some, there's a lot more where that came from", "I'm the Plug", "What a Time to Be Alive"],
		["Mutombo with the bitches, you keep getting rejected", "Jumpman", "What a Time to Be Alive"],
		["Banners are ready in case we need to retire your jersey", "30 for 30 Freestyle", "What a Time to Be Alive"],
		["Too mix up in drama to free my mind", "Hush Up the Silence", ""],
		["Jealous people around me, I need to change my life", "Hush Up the Silence", ""],
		["Envy and jealousy is everything I wish upon my enemies", "Wanna Know (Remix)", ""],
		["You made a couple chops and now you think you Chapo", "Two Birds, One Stone", ""],
		["My accountant say you sinking like the Titanic", "Sneakin'", ""],
		["When you see your enemy somewhere in the club and you realize, he just not in a position to reciprocate your energy", "Wu-Tang Forever", "Nothing Was the Same"],
		["Wish you would learn to love people and use things, and not the other way around", "Connect", "Nothing Was the Same"],
		["Please come outside the house and show yourself, so I can say it to your face", "Free Smoke", "More Life"],
		["We don't need to hear about a next man", "No Long Talk", "More Life"],
		["If it's a chit-chat ting, better talk nice", "No Long Talk", "More Life"],
		["Move from me when you're extra", "Blem", "More Life"],
		["Don't come around thinking you getting saved", "Portland", "More Life"],
		["Taller in person, you'll see when we meet", "KMT", "More Life"],
		["It's a joke, but you say you real, I don't understand", "Can't Have Everything", "More Life"],
		["Everything that went around is coming back around", "Can't Have Everything", "More Life"],
		["I must be coaching cause I'm not playing with them", "Can't Have Everything", "More Life"],
		["Look like you hiding your problems", "Fake Love", "More Life"],
		["That's when they smile in my face, whole time they wanna take my place", "Fake Love", "More Life"],
		["Dissing, but got pictures with me smiling though", "Do Not Disturb", "More Life"],
		["All the things I know, I still been silent though", "Do Not Disturb", "More Life"],
		["I been moving calm, don't start no trouble with me", "God's Plan", "Scorpion"],
		["Tryna keep it peaceful is a struggle for me", "God's Plan", "Scorpion"],
		["It's a lot of bad things that they wishing and wishing and wishing on me", "God's Plan", "Scorpion"],
		["Talking to me like I'm slowing down, opinions over statistics, of course", "Diplomatic Immunity", "Scary Hours"],
		["Come at me and all you'll get is the ballistic report", "Diplomatic Immunity", "Scary Hours"],
		["They try to compare us, but like a job straight outta high school there's no U-N-I", "Diplomatic Immunity", "Scary Hours"],
		["Tell 'em I don't wanna link like a broken necklace", "Diplomatic Immunity", "Scary Hours"],
		["I'll be in better company with my own reflection", "Diplomatic Immunity", "Scary Hours"],
		["I don't play no games boy, I'm at your head", "Bring It Back", ""],
		["Now you gotta own up to that stuff you said", "Bring It Back", ""],
		["Take a shot for me", "Shot for Me"],
		["She says 'I know you changed I never see you cause you're always busy doing things'", "Shot for Me"],
		["Once I get to snappin' ain't nobody safe", "Bring It Back", ""],
		["Reality gon' hit ya or we gon' hit ya", "Bring It Back", ""],
		["I hit her, gave her back to the city, she home", "Walk It Talk It", ""],
		["Say that we been beefing dog, but you on your own", "Walk It Talk It", ""],
		["Their actions out of character even when they rehearse", "Emotionless", "Scorpion"],
		["All these people takin' miles when you give 'em an inch", "Emotionless", "Scorpion"],
		["I been moving calm, don't start no trouble with me", "God's Plan", "Scorpion"],
		["Hate me, never met me in the flesh", "I'm Upset", "Scorpion"],
		["They be watchin' what they say. Especially when it's to my face", "Can't Take a Joke", "Scorpion"],
		["Backstabbed so many times I started walkin' backwards", "Sandra's Rose", "Scorpion"],
		["Only lackin' I can do is my lack of responses", "Is There More", "Scorpion"],
		["People are only as tough as they phone allows them to be", "Peak", "Scorpion"],
	];

	// Only More Life lyrics
	const lyricsMoreLife = [
		["More life, more everything", "Free Smoke", "More Life"],
		["Free smoke, free smoke", "Free Smoke", "More Life"],
		["Where you at? I never see you", "Free Smoke", "More Life"],
		["Please come outside the house and show yourself, so I can say it to your face", "Free Smoke", "More Life"],
		["We don't need to hear about a next man", "No Long Talk", "More Life"],
		["If it's a chit-chat ting, better talk nice", "No Long Talk", "More Life"],
		["You tryna date her and she been, let me walk twice", "No Long Talk", "More Life"],
		["Passionate from miles away", "Passionfruit", "More Life"],
		["Passin' up on my old ways", "Passionfruit", "More Life"],
		["Don't pick up the pieces, just leave it for now. They keep fallin' apart", "Passionfruit", "More Life"],
		["Worried about taking my lane, they ain't even got on my road", "Jorja Interlude", "More Life"],
		["Never chase it, let it come to you", "Jorja Interlude", "More Life"],
		["More chune for your headtop, so watch how you speak on my name", "Jorja Interlude", "More Life"],
		["You need me to get that stuff together, so we can get together", "Get It Together", "More Life"],
		["I cannot tell who is my friend", "Madiba Riddim", "More Life"],
		["I need distance between me and them", "Madiba Riddim", "More Life"],
		["Gonna have to teach me how to love you again", "Madiba Riddim", "More Life"],
		["God knows I'm trying for you", "Madiba Riddim", "More Life"],
		["Your mind impure, soul I possess", "Madiba Riddim", "More Life"],
		["My heart is way too frozen to get broken", "Madiba Riddim", "More Life"],
		["I seen man turn fool for the money one too many times", "Madiba Riddim", "More Life"],
		["I seen some girls turn they back on they best friend from time", "Madiba Riddim", "More Life"],
		["I heard you say things that you can't take back girl", "Madiba Riddim", "More Life"],
		["People change, I'm not surprised", "Madiba Riddim", "More Life"],
		["Who keeps bringing more? I've had too many", "Blem", "More Life"],
		["I'm blem for real, I might just say how I feel", "Blem", "More Life"],
		["Don't switch on me, I got big plans", "Blem", "More Life"],
		["We need to forward to the islands and get you gold, no spray tans", "Blem", "More Life"],
		["I need you to stop runnin' back to your ex, he's a wasteman", "Blem", "More Life"],
		["I wanna know, how come we can never slash and stay friends?", "Blem", "More Life"],
		["I know what I like, I know how I wanna live my life, I donâ€™t need no advice", "Blem", "More Life"],
		["You're not here and we both know why", "Blem", "More Life"],
		["Move from me when you're extra", "Blem", "More Life"],
		["I know we canâ€™t keep it together forever, cause youâ€™re crazy sometimes", "Blem", "More Life"],
		["Tat on my ribs like I do not know what permanent is", "Gyalchester", "More Life"],
		["They want me gone, wait for the kicker, bury me now and I only get bigger", "Gyalchester", "More Life"],
		["Stay at the top like I'm stuck", "Gyalchester", "More Life"],
		["She wanna get married tonight, but I can't take a knee, cause I'm wearin' all white", "Gyalchester", "More Life"],
		["Me and my broski are twins, but we don't look alike", "Gyalchester", "More Life"],
		["I don't take naps. Me and the money are way too attached to go and do that", "Gyalchester", "More Life"],
		["My side girl got a 5S with the screen cracked, still hit me back right away,", "Portland", "More Life"],
		["Tryna show the dogs brighter days", "Portland", "More Life"],
		["Don't come around thinking you getting saved", "Portland", "More Life"],
		["She complaining how I'm late, I ain't know it was a date", "Sacrifices", "More Life"],
		["It's a marathon, not a sprint, but I still gotta win the race", "Sacrifices", "More Life"],
		["I'm still posted up where you first found me", "Nothings Into Somethings", "More Life"],
		["Your heart is hard to carry after dark", "Teenage Fever", "More Life"],
		["You're to blame for what we could have been", "Teenage Fever", "More Life"],
		["Your friends are scared to tell you you're in too far", "Teenage Fever", "More Life"],
		["I met someone new last night and we kicked it and I'm going back there tonight", "Teenage Fever", "More Life"],
		["Out of body, that's just how I feel when I'm around you, shawty", "Teenage Fever", "More Life"],
		["You say the word, I'm on the way", "Teenage Fever", "More Life"],
		["This stuff feels like teenage fever. I'm not scared of it, she ain't either", "Teenage Fever", "More Life"],
		["Love is just not in my plans, not even takin' a chance", "KMT", "More Life"],
		["How long I been on this streak? Dream about work in my sleep", "KMT", "More Life"],
		["You don't know nothing about me", "KMT", "More Life"],
		["Life for my bruddas is deep, long as they all on they feet", "KMT", "More Life"],
		["Taller in person, you'll see when we meet", "KMT", "More Life"],
		["Went and got diplomas, and we still going dumb", "Lose You", "More Life"],
		["I'm in it for the glory, not the honor mention", "Lose You", "More Life"],
		["Better attitude, we'll see where it gets me", "Lose You", "More Life"],
		["I know I deserve more, I just never said it", "Lose You", "More Life"],
		["People like you more when your working towards something, not when you have it", "Lose You", "More Life"],
		["When did all the things I mean from the bottom of my heart start to lose meaning?", "Lose You", "More Life"],
		["You're mindful of it all when your mind full of it all", "Lose You", "More Life"],
		["I know what we're both thinking even when you're quiet", "Lose You", "More Life"],
		["Sometimes I gotta just make sure that I didn't lose you", "Lose You", "More Life"],
		["It's the boy, but I'm still the man", "Can't Have Everything", "More Life"],
		["It's a joke, but you say you real, I don't understand", "Can't Have Everything", "More Life"],
		["Me and all the dogs acting like some dogs", "Can't Have Everything", "More Life"],
		["I don't stop, man I'm stuck on go", "Can't Have Everything", "More Life"],
		["I went off in the '16, give me '17", "Can't Have Everything", "More Life"],
		["Want a lot, can't have everything but I want everything", "Can't Have Everything", "More Life"],
		["Everything that went around is coming back around", "Can't Have Everything", "More Life"],
		["I must be coaching cause I'm not playing with them", "Can't Have Everything", "More Life"],
		["Watch out for me, I'm about to glow", "Glow", "More Life"],
		["But jealousy is just love and hate at the same time", "Over My Dead Body"],
		["I still have my guard up, blame this thing I'm part of", "Glow", "More Life"],
		["You said that you think about me every day", "Since Way Back", "More Life"],
		["You see that I've been going through it, hoping everything's okay", "Since Way Back", "More Life"],
		["I can't help but wonder how you've been babe", "Since Way Back", "More Life"],
		["What are you on? Gotta let me know something", "Since Way Back", "More Life"],
		["I've been down so long, it look like up to me", "Fake Love", "More Life"],
		["I got fake people showing fake love to me", "Fake Love", "More Life"],
		["Look like you hiding your problems", "Fake Love", "More Life"],
		["Just when it look out of reach, I reach back like one-three", "Fake Love", "More Life"],
		["That's when they smile in my face, whole time they wanna take my place", "Fake Love", "More Life"],
		["Vibe switch like night and day", "Fake Love", "More Life"],
		["I want you to myself, but I know you just left someone else", "Ice Melts", "More Life"],
		["Patient as could be but I still need some satisfaction, a little less talk and a little more action", "Ice Melts", "More Life"],
		["I wanna see you do more in this life if we taking it there", "Ice Melts", "More Life"],
		["See you when I see the real thing getting realer and realer", "Ice Melts", "More Life"],
		["Dissing, but got pictures with me smiling though", "Do Not Disturb", "More Life"],
		["All the things I know, I still been silent though", "Do Not Disturb", "More Life"],
		["Saw a side of myself that I just never knew", "Do Not Disturb", "More Life"],
		["More blessings because I'm generous", "Do Not Disturb", "More Life"],
		["Can\t describe what my life is like when she asks about it", "Do Not Disturb", "More Life"],
		["Seasons go by like I'm binge watchin'", "Do Not Disturb", "More Life"],
		["More Life", "Do Not Disturb", "More Life"],
		["I don't have no time to be no Romeo", "Do Not Disturb", "More Life"],
	];

	// Only Scary Hours lyrics
	const lyricsScaryHours = [
		["I been moving calm, don't start no trouble with me", "God's Plan", "Scary Hours"],
		["Tryna keep it peaceful is a struggle for me", "God's Plan", "Scary Hours"],
		["You know how I like it when you loving on me", "God's Plan", "Scary Hours"],
		["I don't wanna die for them to miss me", "God's Plan", "Scary Hours"],
		["Hope I got some brothers that outlive me", "God's Plan", "Scary Hours"],
		["They gon' tell the story, it was different with me", "God's Plan", "Scary Hours"],
		["I feel good, sometimes I don't", "God's Plan", "Scary Hours"],
		["Might go down a G.O.D.", "God's Plan", "Scary Hours"],
		["So cry if you need to, but I can't stay to watch you that's the wrong thing to do", "Doing It Wrong"],
		["It's a lot of bad things that they wishing and wishing and wishing on me", "God's Plan", "Scary Hours"],
		["She say, \"Do you love me?\" I tell her, \"Only partly\" I only love my bed and my momma, I'm sorry", "God's Plan", "Scary Hours"],
		["Imagine if I never met the broskies", "God's Plan", "Scary Hours"],
		["God's plan, I can't do this on my own", "God's Plan", "Scary Hours"],
		["Talking to me like I'm slowing down, opinions over statistics, of course", "Diplomatic Immunity", "Scary Hours"],
		["Come at me and all you'll get is the ballistic report", "Diplomatic Immunity", "Scary Hours"],
		["Girls hugging me then asking me, \"What scent that is, boy?\"", "Diplomatic Immunity", "Scary Hours"],
		["The one with the fewest lies and the truest ties", "Diplomatic Immunity", "Scary Hours"],
		["They try to compare us, but like a job straight outta high school there's no U-N-I", "Diplomatic Immunity", "Scary Hours"],
		["I broke spirits that I never meant to", "Diplomatic Immunity", "Scary Hours"],
		["Champagne is the alias", "Diplomatic Immunity", "Scary Hours"],
		["Dirty 30, working on me", "Diplomatic Immunity", "Scary Hours"],
		["We live in a generation of not being in love and not being together", "Doing It Wrong"],
		["Something's been missing you know it, oh oh, she knows it", "Doing It Wrong"],
		["Tired of women that may tag me in pictures airing my dirty laundry", "Diplomatic Immunity", "Scary Hours"],
		["I got the sauce and now shorties keep claiming preggo", "Diplomatic Immunity", "Scary Hours"],
		["Wakin' up at 6 PM like, \"Where does the day go?\"", "Diplomatic Immunity", "Scary Hours"],
		["Closed off but I could never stay closed", "Diplomatic Immunity", "Scary Hours"],
		["That just pushed me to do the things we all couldn't", "Diplomatic Immunity", "Scary Hours"],
		["Protection that God gave me", "Diplomatic Immunity", "Scary Hours"],
		["Cause you'll say you love me, and I'll end up lying and say I love you, too", "Doing It Wrong"],
		["I think I killed e'rybody in the game last year, man", "Over My Dead Body"],
		["Nowadays it's six figures when they tax me oh well, I guess you lose some and win some long as the outcome is income", "Over My Dead Body"],
		["Tell 'em I don't wanna link like a broken necklace", "Diplomatic Immunity", "Scary Hours"],
		["I'll be in better company with my own reflection", "Diplomatic Immunity", "Scary Hours"],
		["Inshallah, I hope the mission keeps on getting clearer", "Diplomatic Immunity", "Scary Hours"],
	];

	// Only Scorpion lyrics
	const lyricsScorpion = [
		["Seen this movie a hundred times, I know where it's headed", "Survival", "Scorpion"],
		["Think my soul has been marked, there's a hole in my heart", "Survival", "Scorpion"],
		["Always got a ace up my sleeve for whatever was dealt", "Survival", "Scorpion"],
		["I stopped askin' myself and I started feelin' myself", "Survival", "Scorpion"],
		["Now I gotta deal with all this drama and deal with myself", "Survival", "Scorpion"],
		["I don't know nobody else that's doing this", "Nonstop", "Scorpion"],
		["Now they wanna know me since I hit the top", "Nonstop", "Scorpion"],
		["And she's the reason it happened, but she's overreacting and it's all because she don't want things to change", "Doing It Wrong"],
		["This a Rollie, not a stopwatch, it don't ever stop", "Nonstop", "Scorpion"],
		["Pinky ring 'til I get a wedding ring", "Nonstop", "Scorpion"],
		["Love my brothers, cut 'em in on anything", "Nonstop", "Scorpion"],
		["Only obligation is to tell it straight. So much on my plate I gotta delegate", "Elevate", "Scorpion"],
		["She is not the type that likes to take things slowly", "Elevate", "Scorpion"],
		["I wanna thank God for workin' way harder than Satan", "Elevate", "Scorpion"],
		["Me and all the guys found a better way", "Elevate", "Scorpion"],
		["All this happen for myself and my family", "Elevate", "Scorpion"],
		["I know the truth is you won't love me until I'm gone", "Emotionless", "Scorpion"],
		["Their actions out of character even when they rehearse", "Emotionless", "Scorpion"],
		["I gotta bring my brothers or else I feel out of place", "Emotionless", "Scorpion"],
		["All these people takin' miles when you give 'em an inch", "Emotionless", "Scorpion"],
		["All these followers but who gon' follow me to the end. I guess I'll make it to the end and I'ma find out then", "Emotionless", "Scorpion"],
		["I been moving calm, don't start no trouble with me", "God's Plan", "Scorpion"],
		["Tryna keep it peaceful is a struggle for me", "God's Plan", "Scorpion"],
		["You know how I like it when you loving on me", "God's Plan", "Scorpion"],
		["I don't wanna die for them to miss me", "God's Plan", "Scorpion"],
		["Hope I got some brothers that outlive me", "God's Plan", "Scorpion"],
		["They gon' tell the story, it was different with me", "God's Plan", "Scorpion"],
		["I feel good, sometimes I don't", "God's Plan", "Scorpion"],
		["Might go down a G.O.D.", "God's Plan", "Scorpion"],
		["It's a lot of bad things that they wishing and wishing and wishing on me", "God's Plan", "Scorpion"],
		["She say, \"Do you love me?\" I tell her, \"Only partly\" I only love my bed and my momma, I'm sorry", "God's Plan", "Scorpion"],
		["Imagine if I never met the broskies", "God's Plan", "Scorpion"],
		["God's plan, I can't do this on my own", "God's Plan", "Scorpion"],
		["Got a lot of blood and it's cold. They keep tryna get me for my soul", "I'm Upset", "Scorpion"],
		["I still got like seven years of doin' what I want", "I'm Upset", "Scorpion"],
		["End up gettin' loose and gettin' pictures from my ex", "I'm Upset", "Scorpion"],
		["She don't even love me, she just puttin' on a front", "I'm Upset", "Scorpion"],
		["Hate me, never met me in the flesh", "I'm Upset", "Scorpion"],
		["I've never been the type to make amends", "8 Out of 10", "Scorpion"],
		["I don't like to talk when there's nothin' else left to say", "8 Out of 10", "Scorpion"],
		["Whatever you did, it is what it is", "Mob Ties", "Scorpion"],
		["They want me gone but don't know why", "Mob Ties", "Scorpion"],
		["S Class, G Class, lotta class", "Mob Ties", "Scorpion"],
		["Lead the league in scorin', man, but look at my assists", "Mob Ties", "Scorpion"],
		["I do not forget a thing, I'm patient, it's a gift ", "Mob Ties", "Scorpion"],
		["Try to tell 'em they ain't got to do it, they insist ", "Mob Ties", "Scorpion"],
		["Skit around ends with the bros and I'm kitted to the toes", "Can't Take a Joke", "Scorpion"],
		["We live by the code, reputation to uphold", "Can't Take a Joke", "Scorpion"],
		["I be tryna laugh with the bros but they can't take a joke", "Can't Take a Joke", "Scorpion"],
		["They be watchin' what they say. Especially when it's to my face", "Can't Take a Joke", "Scorpion"],
		["Worms, I just opened up a can of those", "Sandra's Rose", "Scorpion"],
		["Life too short, I gotta get it before they blow the whistle", "Sandra's Rose", "Scorpion"],
		["I'm the chosen one, flowers never pick themselves", "Sandra's Rose", "Scorpion"],
		["I find it funny how I keep on talkin' and commas increase", "Sandra's Rose", "Scorpion"],
		["Backstabbed so many times I started walkin' backwards", "Sandra's Rose", "Scorpion"],
		["Can of worms and I'm the early bird", "Sandra's Rose", "Scorpion"],
		["I don't know who's protectin' me but we hit it off", "Sandra's Rose", "Scorpion"],
		["Ten of us, we movin' as one", "Talk Up", "Scorpion"],
		["I'm so proud of who I've become", "Talk Up", "Scorpion"],
		["Intentions are pure, they cannot tell me relax", "Talk Up", "Scorpion"],
		["My money is young, my problems are old. I promise I'm bridgin' the gap", "Talk Up", "Scorpion"],
		["Only holdin' up I do is my end of the bargain", "Is There More", "Scorpion"],
		["Only beggin' that I do is me beggin' your pardon", "Is There More", "Scorpion"],
		["Only lyin' I do is lyin' out in the tropics", "Is There More", "Scorpion"],
		["Only cryin' I do is cryin' from laughin' 'bout it", "Is There More", "Scorpion"],
		["Only lackin' I can do is my lack of responses", "Is There More", "Scorpion"],
		["Only rest that I do is \"Where the rest of my commas?\"", "Is There More", "Scorpion"],
		["When life comin' at you from all angles and sides", "Is There More", "Scorpion"],
		["They don't wanna see that you smilin' from inside", "Is There More", "Scorpion"],
		["I'm in control of my destiny, never in doubt", "Is There More", "Scorpion"],
		["If I can't make it with you, I'll make it without", "Is There More", "Scorpion"],
		["They say take the good with the bad, I'll take it without", "Is There More", "Scorpion"],
		["My moral compass is janky, it breaks in the South", "Is There More", "Scorpion"],
		["Too many Walt Disney characters, mouses and goofs", "Is There More", "Scorpion"],
		["It's too bad reality checks don't cover the balances due", "Is There More", "Scorpion"],
		["What you got, time on your hands or time on your side?", "Is There More", "Scorpion"],
		["Is there more to life than just when I'm feelin' alive?", "Is There More", "Scorpion"],
		["Treat you like princess", "Peak", "Scorpion"],
		["You know I want it all and then some shout out to Asian girls, let the lights dim some", "Over My Dead Body"],
		["Talk used to be cheap, nowadays it's free", "Peak", "Scorpion"],
		["People are only as tough as they phone allows them to be", "Peak", "Scorpion"],
		["I found my peace, I'm about to say my piece", "Peak", "Scorpion"],
		["You gon' make me turn up on you", "Peak", "Scorpion"],
		["I think you're changin' your mind. Startin' to see it in your eyes", "Summer Games", "Scorpion"],
		["Summer just started and we're already done", "Summer Games", "Scorpion"],
		["Be warm with me when it's freezin' outside", "Summer Games", "Scorpion"],
		["I kept it decent, even the secrets. Kept it between you and I", "Summer Games", "Scorpion"],
		["Breakin' me down when I'm already down", "Summer Games", "Scorpion"],
		["Leaving me, Dippin' out on me, Already got what you needed, I guess", "Jaded", "Scorpion"],
		["Learned yourself through me", "Jaded", "Scorpion"],
		["That's why I'm not with nobody. 'Cause I don't wanna hurt nobody", "Jaded", "Scorpion"],
		["Still got love for you, mami", "Jaded", "Scorpion"],
		["I know you wanna be somebody. Even if you gotta leave somebody", "Jaded", "Scorpion"],
		["Yes I'm hurting, yes I'm jaded", "Jaded", "Scorpion"],
		["I always want the truth, but it's dangerous", "Jaded", "Scorpion"],
		["Said you need some time but I should stick around, for what?", "Jaded", "Scorpion"],
		["You played me, you played me", "Jaded", "Scorpion"],
		["How you even managing to keep straight faces in all the pictures that I seen lately", "Jaded", "Scorpion"],
		["You're old enough, but you're still a baby", "Jaded", "Scorpion"],
		["Had a man last year, life goes on", "Nice For What", "Scorpion"],
		["That's a real one in your reflection", "Nice For What", "Scorpion"],
		["I want my baby to have your eyes", "Finesse", "Scorpion"],
		["I'm going against my own advice", "Finesse", "Scorpion"],
		["I can't even lie, I'd rather stay inside", "Finesse", "Scorpion"],
		["Can't be in a room with you and stand on different sides", "Finesse", "Scorpion"],
		["You stay on my mind all the time", "Finesse", "Scorpion"],
		["Who's gonna love you on your worst day?", "Ratchet Happy Birthday", "Scorpion"],
		["I miss the days that you was all mine", "Ratchet Happy Birthday", "Scorpion"],
		["Haven't been official in a long time", "Ratchet Happy Birthday", "Scorpion"],
		["To be, to feel, and fill that emptiness inside you", "Ratchet Happy Birthday", "Scorpion"],
		["Time gets to tickin' and it takes a toll", "That's How You Feel", "Scorpion"],
		["Sidetracking me when I was good to you. You were somebody I would stand behind", "That's How You Feel", "Scorpion"],
		["Work all winter, shine all summer", "That's How You Feel", "Scorpion"],
		["Are you riding, say you'll never ever leave from beside me, 'cause I want you, and I need you and I'm down for you always.", "In My Feelings"],
		["Drink 'til the sun up. Grind 'til you come up", "That's How You Feel", "Scorpion"],
		["Look the new me is really still the real me", "In My Feelings", "Scorpion"],
		["'Cause I've been goin' off and they don't know when it's stoppin'", "In My Feelings", "Scorpion"],
		["When I take you shoppin' you spend it like you earned it", "In My Feelings", "Scorpion"],
		["I thought you were the one from the jump that confirmed it", "In My Feelings", "Scorpion"],
		["I'm in control of my destiny, never in doubt / If I can't make it with you, I'll make it without.", "Is there more"]
		// eslint-disable-next-line no-unexpected-multiline
			["Assuming the worst 'cause I haven't heard from you all weekend", "After Dark", "Scorpion"],
		["Your silence is drivin' me up the wall", "After Dark", "Scorpion"],
		["I cannot tell if you're ducking calls or missing calls", "After Dark", "Scorpion"],
		["I wanna make you a priority, I wanna let you know there's more to me", "After Dark", "Scorpion"],
		["I wanna have your faith restored in me", "After Dark", "Scorpion"],
		["Being honest, I don't really know what patience is", "Final Fantasy", "Scorpion"],
		["I like best when you're fresh faced and no foundation", "Final Fantasy", "Scorpion"],
		["I always need a glass of wine by sundown", "Final Fantasy", "Scorpion"],
		["You got options, but I been chosen", "Final Fantasy", "Scorpion"],
		["To deal with you the way you like", "Final Fantasy", "Scorpion"],
		["Now it's rough times, I'm out here on front lines", "March 14 ", "Scorpion"],
		["I wanted it to be different because I've been through it", "March 14 ", "Scorpion"],
	];
	// ALL lyrics (Adds them all together, if no category is picked)
	const lyricsAll = lyricsBae.concat(lyricsLit, lyricsSavage, lyricsSimp, lyricsIdfwu, lyricsOther, lyricsCrewLove, lyricsScaryHours, lyricsScorpion, lyricsMoreLife);

	// getting random number based on amount of numbers in array
	const randomNumber = Math.floor(Math.random() * (lyricsAll.length));

	const responseBody = {
		text: "> " + "_" + lyricsAll[randomNumber][0] + "_" + " - " + lyricsAll[randomNumber][1],
	};

	return responseBody;
}


client.on("ready", () => {
	console.log(`Logged in as ${client.user.tag}!`);
	client.user.setPresence({
		activity: {
			name: "/drakesays",
		},
	});
});

client.on("message", (msg) => {
	if (!msg.content.startsWith(prefix) || msg.author.bot) return;
	const randomQuote = getLyric();
	msg.channel.send(randomQuote.text);
});

client.login(process.env.DISCORD_BOT_TOKEN);
